import { Hono } from "hono";
import { z } from "zod";
import { zValidator } from "@hono/zod-validator";
import { eq } from "drizzle-orm";
import { db, queryClient } from "../db/index";
import { userDetail, transactions, userItems } from "../db/schema";
import { createXenditInvoice } from "../services/xendit.service";
import { getProductFromERP } from "../services/erp.service";
import { checkIdempotency } from "../lib/idempotency";
import { addErpJob } from "../queue/producer";
import { redisClient } from "../queue/connection";
import { env } from "../lib/env";
import { AppError } from "../middleware/error-handler";
import { initiateRateLimiter } from "../middleware/rate-limit.middleware";
import type {
  XenditWebhookPayload,
  InitiatePaymentResponse,
} from "../types/index";

// =============================================================================
// VALIDATION SCHEMAS
// =============================================================================

const initiatePaymentSchema = z.object({
  phone: z.string().regex(/^(\+62|62|0)8[1-9][0-9]{6,10}$/, 'Format nomor HP tidak valid'),
  items: z
    .array(
      z.object({
        item_code: z.string().min(1, "item_code is required"),
        item_name: z.string().min(1, "item_name is required"),
        quantity: z.number().int().positive("Quantity must be a positive integer"),
        content: z
            .array(
              z.object({
                item_numbers: z.string().min(1, "Item_numbers is rquired"),
                item_address: z.string().min(1," Item_address is required"),
                item_style: z
                  .array(
                    z.object({
                      item_font: z.string().min(1, "item_font is required"),
                      font_style: z.string().min(1, "font_style is reqired"),
                    })
                  )
              })
            )
      })
    )
    .min(1, "At least one item is required"),
});

// =============================================================================
// ROUTER
// =============================================================================

export const paymentRoutes = new Hono();

// =============================================================================
// POST /api/payment/initiate
// =============================================================================

/**
 * Creates a new payment invoice via Xendit.
 *
 * Prerequisites: User must already be registered via POST /api/user-initiate.
 *
 * Flow:
 *   1. Validate request body
 *   2. Look up user by phone (must exist — registered via /api/user-initiate)
 *   3. Fetch price for each item from ERP (price NEVER comes from client)
 *   4. Calculate total_amount from ERP-fetched prices
 *   5. Insert transaction row (status: PENDING)
 *   6. Insert line items into `user_items`
 *   7. Call Xendit API to create invoice (with redirect URLs)
 *   8. Update transaction with Xendit invoice ID and invoice_url
 *   9. Return invoice_url and transaction_id to client
 */
paymentRoutes.post(
  "/initiate",
  initiateRateLimiter,       // Rate limit
  zValidator("json", initiatePaymentSchema),
  async (c) => {
    const body = c.req.valid("json");

    // ─── Step 1: Look up user by phone ──────────────────────────────────
    const user = await db.query.userDetail.findFirst({
      where: eq(userDetail.phone, body.phone),
    });

    if (!user) {
      return c.json(
        { success: false, message: "User not found. Please register via /api/user-initiate first." },
        404
      );
    }

    // ─── Step 2: Fetch price for each item from ERP ─────────────────────
    const enrichedItems = await Promise.all(
      body.items.map(async (item) => {
        const erpProduct = await getProductFromERP(item.item_code);
        return {
          item_code:  item.item_code,
          item_name:  item.item_name,
          quantity:   item.quantity,
          content:    item.content,
          rate:       erpProduct.standard_rate,   // FROM ERP — never from client
          uom:        erpProduct.stock_uom ?? 'Pcs',
          warehouse:  env.ERP_WAREHOUSE,
        };
      })
    );

    // ─── Step 3: Calculate total amount from ERP prices ──────────────────
    const totalAmount = enrichedItems.reduce(
      (sum, i) => sum + i.rate * i.quantity,
      0
    );

    // ─── Step 4: Insert transaction (PENDING) ──────────────────────────
    // The UUID is auto-generated by PostgreSQL and used as Xendit's external_id.
    const [transaction] = await db
      .insert(transactions)
      .values({
        userId: user.id,
        xenditExternalId: crypto.randomUUID(), // placeholder until confirmed by Xendit response
        status: "PENDING",
        totalAmount: totalAmount.toString(),
      })
      .returning();

    if (!transaction) {
      throw new AppError(500, "Failed to create transaction");
    }

    // Use the transaction UUID as the Xendit external_id (update in DB)
    await db
      .update(transactions)
      .set({ xenditExternalId: transaction.id })
      .where(eq(transactions.id, transaction.id));

    // ─── Step 5: Insert line items ─────────────────────────────────────
    await db.insert(userItems).values(
      enrichedItems.map((item) => ({
        transactionId: transaction.id,
        itemCode: item.item_code,
        itemName: item.item_name,
        quantity: item.quantity,
        content: item.content,
      }))
    );

    // ─── Step 6: Call Xendit API (with redirect URLs) ──────────────────
    const xenditInvoice = await createXenditInvoice({
      external_id: transaction.id, // UUID as external_id for direct correlation
      amount: totalAmount,
      description: `Payment for ${body.items.length} item(s)`,
      currency: env.ERP_CURRENCY,
      success_redirect_url: `${env.FE_BASE_URL}/thank-you?order_id=${transaction.id}`,
      failure_redirect_url: `${env.FE_BASE_URL}/payment-failed?order_id=${transaction.id}`,
      items: enrichedItems.map((item) => ({
        name: item.item_name,
        quantity: item.quantity,
        price: item.rate,
        category: "Product",
      })),
    });

    // ─── Step 7: Update transaction with Xendit invoice data ───────────
    await db
      .update(transactions)
      .set({
        xenditInvoiceId: xenditInvoice.id,
        invoiceUrl: xenditInvoice.invoice_url,
        updatedAt: new Date(),
      })
      .where(eq(transactions.id, transaction.id));

    // ─── Step 8: Return invoice URL ───────────────────────────────────
    const response: InitiatePaymentResponse = {
      success: true,
      invoice_url: xenditInvoice.invoice_url,
      transaction_id: transaction.id,
    };

    return c.json(response, 201);
  }
);

// =============================================================================
// POST /api/payment/webhook
// =============================================================================

/**
 * Xendit Webhook Handler
 *
 * This endpoint MUST handle race conditions and duplicate webhook retries.
 * It implements a 4-layer defense against duplicate processing:
 *
 * Layer 1: x-callback-token signature verification
 * Layer 2: Redis SETNX idempotency (24h TTL) — stops duplicates immediately
 * Layer 3: SELECT ... FOR UPDATE row-level DB lock — prevents concurrent DB writes
 * Layer 4: Status guard — if already PAID, skip and return 200
 */
paymentRoutes.post("/webhook", async (c) => {
  // ─── Layer 1: Verify Xendit callback signature ──────────────────────────
  const callbackToken = c.req.header("x-callback-token");

  if (!callbackToken || callbackToken !== env.XENDIT_WEBHOOK_TOKEN) {
    console.warn("[Webhook] Invalid or missing x-callback-token");
    return c.json({ error: "Forbidden" }, 403);
  }

  // Parse the webhook payload
  let payload: XenditWebhookPayload;
  try {
    payload = await c.req.json<XenditWebhookPayload>();
  } catch {
    return c.json({ error: "Invalid JSON payload" }, 400);
  }

  // We only care about PAID events — ignore others (e.g., EXPIRED)
  if (payload.status !== "PAID") {
    console.log(`[Webhook] Ignoring webhook with status: ${payload.status}`);
    return c.json({ received: true }, 200);
  }

  const webhookId = payload.id;
  const externalId = payload.external_id; // This is our transaction UUID

  if (!webhookId || !externalId) {
    return c.json({ error: "Missing id or external_id in payload" }, 400);
  }

  // ─── Layer 2: Redis idempotency check (SETNX) ──────────────────────────
  //
  // RACE CONDITION PROTECTION:
  // Xendit may send the same webhook multiple times (retries on timeout/failure).
  // The atomic SETNX ensures only the FIRST delivery proceeds.
  // All subsequent deliveries see the key already set and return 200 immediately.
  //
  const isNew = await checkIdempotency(redisClient, webhookId, 86400);

  if (!isNew) {
    // This is a duplicate webhook delivery — already processed
    console.log(`[Webhook] Duplicate webhook detected (id: ${webhookId}). Returning 200.`);
    return c.json({ received: true }, 200);
  }

  // ─── Layers 3 & 4: DB row-level lock + status guard ────────────────────
  //
  // RACE CONDITION PROTECTION:
  // Even if two requests slip past the Redis check simultaneously
  // (e.g., Redis restarted), the SELECT ... FOR UPDATE ensures only
  // one DB transaction can update the row at a time.
  //
  // We use a raw SQL transaction for the FOR UPDATE lock.
  // Drizzle does not currently support SELECT ... FOR UPDATE natively.
  //
  type LockedTx = { id: string; status: string; user_id: number };
  let erpJobArgs: { transactionId: string; userId: number } | null = null;

  try {
    // Use postgres-js transaction directly for SELECT ... FOR UPDATE support.
    // Drizzle's db.transaction() wraps the same connection pool, but the
    // tagged-template sql`` syntax (postgres-js native) is the safest way
    // to execute raw parameterized SQL with the correct type mapping.
    await queryClient.begin(async (sql) => {
      // Layer 3: Lock the row — concurrent requests BLOCK here until commit
      const rows = await sql<LockedTx[]>`
        SELECT id, status, user_id
        FROM transactions
        WHERE id = ${externalId}
        FOR UPDATE
      `;

      const lockedTransaction = rows[0];

      if (!lockedTransaction) {
        console.warn(`[Webhook] Transaction not found for external_id: ${externalId}`);
        return; // rolls back automatically if we throw, but here we just skip
      }

      // ─── Layer 4: Status guard ────────────────────────────────────────
      // If already PAID (e.g., processed by a concurrent request that won
      // the Redis race before Redis dedup caught up), just exit cleanly.
      if (lockedTransaction.status === "PAID") {
        console.log(`[Webhook] Transaction ${externalId} already PAID. Skipping.`);
        return;
      }

      // ─── Update status to PAID ────────────────────────────────────────
      await sql`
        UPDATE transactions
        SET status = 'PAID', updated_at = NOW()
        WHERE id = ${externalId}
      `;

      console.log(`[Webhook] ✅ Transaction ${externalId} marked as PAID`);

      // Capture job args — addErpJob is called AFTER the DB transaction commits
      // to ensure the ERP job is only enqueued on a successful DB write.
      erpJobArgs = { transactionId: externalId, userId: lockedTransaction.user_id };
    });

    // ─── Enqueue ERP job AFTER DB transaction is committed ───────────────
    if (erpJobArgs !== null) {
      // Non-null assertion: erpJobArgs is set inside the tx callback on success
      const { transactionId, userId } = erpJobArgs as { transactionId: string; userId: number };
      await addErpJob(transactionId, userId);
    }
  } catch (err) {
    console.error("[Webhook] Error processing webhook:", err);
    // Return 500 so Xendit will retry — the Redis key is already set,
    // so the retry will be caught as a duplicate and skipped.
    // To allow retry processing, we need to clear the idempotency key.
    // This is done by deleting it so the next retry can reprocess.
    await redisClient.del(`webhook:idempotency:${webhookId}`);
    return c.json({ error: "Internal server error" }, 500);
  }

  return c.json({ received: true }, 200);
});
